version: "2"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:9292:9292"
    env_file:
      - "config/env.sh"
    links:
      - db
      - webpack
  db:
    image: postgres:9.6
    ports:
      - "0.0.0.0:15432:5432"
    volumes:
      - pg:/var/lib/postgres/data
  webpack:
    build: .
    env_file:
      - "config/env.sh"
    command: bash -c "npm run refresh && npm run start -- --host=0.0.0.0 --port=8080"
    volumes:
      - .:/app
    ports:
      - '8080:8080'
volumes:
  pg:
    external: false
