version: "2"
services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "0.0.0.0:9292:9292"
    env_file:
      - "config/env.sh"
    links:
      - db
  db:
    image: mysql:5.7
    ports:
      - "0.0.0.0:13306:3306"
    env_file:
      - "config/env.sh"
    volumes:
      - db:/var/lib/mysql
volumes:
  db:
    external: false
